### ISSUE TITLE
Support usage outside IPython. For example in Python

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ahuang11/ahlive#16]
If I run the code below as a python script I get `ModuleNotFoundError: No module named 'IPython'`.

I did it because my workflow is normally wrapping things in panels (i.e. HoloViz Panel) for web apps.

Feature Request: Support using ahlive in Panel. Include an example of showing the most performant way to output to a `Gif` pane and a `Video` pane.

```bash
import ahlive as ah
df = ah.open_dataset(label='annual_co2')
ah_df = ah.DataFrame(df, xs='year', ys='co2_ppm')
ah_df.render()
```

![image](https://user-images.githubusercontent.com/42288570/107606389-33525680-6c36-11eb-8dd5-283405316116.png)

**Comment by MarcSkovMadsen** [comment]
Included it the example it would be really nice to know how you could hook into the progress and show that in a `panel.widget.progress` or something similar while the user waits for the rending.

```bash
ANNUAL CO2 | Source: NOAA ESRL | https://www.esrl.noaa.gov/
[########################################] | 100% Completed | 21.1s
```

**Comment by MarcSkovMadsen** [comment]
Got something working https://discourse.holoviz.org/t/panel-feels-ahlive/1847

**Comment by ahuang11** [comment]
Check out integration with panel here https://ahlive.readthedocs.io/en/latest/customizations/animating.html#animate

 But yeah I need to fix no ipython

**Comment by ahuang11** [comment]
That example looks good! If you'd like you can make a PR to the examples page or discussions!
